### DISCUSSION TITLE
How do I enable a custom font?

### DISCUSSION THREAD

**Discussion by Explosion-Scratch** [codesandbox/codesandbox-client#5140] [Q&A] [answered]
I really like the font Fira Code and I want to enable it in CSB, but it's not installed on the virtual codesandbox machine, is there any way to upload either a .woff or .ttf file or import it from google fonts?

**Comment by SaraVieira** [comment, marked as answer]
Hey

Right now we do not have this feature, you can only add custom fonts to the sandbox itself, not to codesandbox.

You can do this with extensions if you are using chrome I was able to do it by downloading `stylebot` and add the following css:

```css
@import url('https://fonts.googleapis.com/css2?family=Fira+Code&display=swap');

.view-lines {
  font-family: 'Fira Code';
}
```


![CleanShot 2020-11-17 at 11 53 07](https://user-images.githubusercontent.com/1051509/99381498-846adc80-28cb-11eb-980a-0c1ada64a04c.png)

And here is the extension: https://stylebot.dev/
