### DISCUSSION TITLE
the CSS react file doesn't work referencing resources (svg, png etc)

### DISCUSSION THREAD

**Discussion by uyriq** [codesandbox/codesandbox-client#6724] [Q&A] [answered]
[https://codesandbox.io/s/github/uyriq/basic-17.1?file=/src/components/MainDashboard.module.css](https://codesandbox.io/s/github/uyriq/basic-17.1?file=/src/components/MainDashboard.module.css)

Good afternoon, I do not know whether to refer to the section QA or should make a new issue. The essence of my question is the following: in the REACT application I use styles. in the style file, for example, in MainDashboard.module.css I write 
```CSS
.mainCircle {
  width: calc(100% - 30px);
  height: 100%;
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: center;
  alignment-content: center;
  background: url("../images/markers.svg") center no-repeat;
  background-size: contain;
}
```
this `background: url("./images/markers.svg")` doesn't work and no display in render. advise me a hack to fix this misbehaving codesandbox
thanks!
