### ISSUE TITLE
cors error in preview

### ISSUE THREAD

**Issue by lucmski** [codesandbox/codesandbox-client#2423]
Hi guys,

Hope you are all well !

In https://codesandbox.io/s/interesting-pike-258z6?fontsize=14, I cannot fetch information from an elasticsearch instance. But i can from http://x0rzkov.hd.free.fr:3000/

I have the following error:
```
TypeError: Network request failed
    at XMLHttpRequest.xhr.onerror (https://258z6.csb.app/node_modules/cross-fetch/dist/browser-ponyfill.js:445:16)
```

To test
```
http://x0rzkov.hd.free.fr:9200/twinttweets/_count?pretty
http://x0rzkov.hd.free.fr:9200/twinttweets/_search?pretty=true&q=*:*
```

elasticsearch.yml
```yaml
cluster.name: "docker-cluster"
# cluster.initial_master_nodes
network.host: 0.0.0.0

node.name: elasticsearch
cluster.initial_master_nodes: elasticsearch
bootstrap.memory_lock: true
#index.blocks.read_only_allow_delete: null
# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1
#discovery.seed_hosts
#discovery.seed_providers
xpack.license.self_generated.type: basic

# ---------------------------------- Network -----------------------------------

# CORS Settings
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length, X-User"

```

Thanks in advance for any help.

Cheers,
L.
