### ISSUE TITLE
File uploads exceeding max upload size result in 500 error

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#4167]
From user: 

I try to upload an `.obj` model from my computer and what I get is this:

![image](https://user-images.githubusercontent.com/35937217/82461666-5c88f080-9ac3-11ea-86bf-65432cef1179.png)

It's size is ~7.2 mb

here is where I got it: https://free3d.com/3d-model/hand-v3--902450.html

## Technical info

**Request response**:

```json
{"errors":{"detail":["Internal server error"]}}
```

**Request headers**:

```yaml
Host: codesandbox.io
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/json;charset=utf-8
Content-Length: 10050761
Origin: https://codesandbox.io
DNT: 1
Referer: https://codesandbox.io/s/react-postprocessing-showcase-demo-7gr13?file=/src/App.js
Connection: keep-alive
# auth cookies
```

**Response headers**:

```yaml
HTTP/2 500 Internal Server Error
date: Wed, 20 May 2020 14:55:20 GMT
content-type: application/json; charset=utf-8
content-length: 47
cache-control: max-age=0, private, must-revalidate
via: 1.1 google
alt-svc: h3-27=":443"; ma=86400, h3-25=":443"; ma=86400, h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 5966e5a43ea44971-DME
cf-request-id: 02d42ddaa0000049718da82200000001
X-Firefox-Spdy: h2
```

_Originally posted by @talentlessguy in https://github.com/codesandbox/codesandbox-client/discussions/4166_

Confirmed in separate sandbox with same file, and another image file - both above 7MB.
